version: "3.3"

services:
  
  
  db:
    container_name: postgres-e-commerce
    image: postgres:12.0-alpine
    expose: 
      - "5432"
    ports:
      - "5432:5432"
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
   
  products:
    container_name: django-e-commerce
    build: .
    image: django-docker:0.0.1
    command: ["./run_web.sh"]
    
    ports:
      - "8000:8000"
    
    depends_on:
      - db
    

    
     

 